### ISSUE TITLE
Nudge Extension JSON

### ISSUE THREAD

**Issue by Maksimuz** [optimizely/library#42]
The example picture:
![image](https://user-images.githubusercontent.com/52075850/60965171-755a3e80-a315-11e9-85b4-1d16896bf4e0.png)

list of configuration properties:

- place of the element: left, right, above, beyond the targeted element

other functionality:

-  dismissable (like in the example)

- only shows up once or everytime

- Background and text color 

who uses such feature:

- facebook

- youtube

**Comment by asaschachar** [comment]
Thanks for opening this suggestion for an extension to be added to our extension library! This is definitely a great idea and we'll update you as soon as we have made progress on it.

**Comment by asaschachar** [comment]
Hi @Maksimuz, I created an example extension for your nudge request (see the [PR referenced above](https://github.com/optimizely/library/pull/43)). Please check it out and let me know if it satisfies your use cases. I've only currently tested it on simple examples, so there are probably some styling corner-cases to improve.

Otherwise let me know what you think and thanks for the suggestion!

**Comment by asaschachar** [comment]
Hi @Maksimuz, I've committed a draft of the extension you were looking for, so I'll be closing this issue. Let us know if it works for you or if you have any other suggestions for improvements or requests for other extensions! Thanks!
